file_path:
 "/mnt/sda/coex_data/track_fail/result_2025_02_07_104018_aimerfeel/"
  # "/mnt/sda/coex_data/result_2024_11_22_144140_lifefourcut_3/"
  # "/mnt/sda/coex_data/track_fail/result_2025_02_07_104112_olens/"

filtered_csv_path: "./yolo_info_filtered.csv"

timestamp_path: '/home/youngsun/vslam/ORB_SLAM3/Examples/timestamp.txt'

hyperparameters:
  conf_threshold: 0.2
  frames_per_sec: 3

