root_dir: /mnt/sda/coex_data/long_sequence
connecting_dir: /home/youngsun/vslam/corl/ConnectingMaps/ORB-SLAM1
sequences:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
date_str: '2025_04_14'
time_str: 092728
# txt_input_path: '/home/youngsun/vslam/corl/ConnectingMaps/ORB-SLAM1/2025_04_14/092728/yolo/9th//four_frame_result/0/txt/images.txt'
# txt_parsed_path: '/home/youngsun/vslam/corl/ConnectingMaps/ORB-SLAM1/2025_04_14/092728/yolo/9th//four_frame_result/0/txt/images_parsed.txt'