connecting_dir: /home/youngsun/vslam/corl/ConnectingMaps/ORB-SLAM1
date_str: '2025_04_14'
final_trajectory_path: /home/youngsun/vslam/corl/ConnectingMaps/ORB-SLAM1/2025_04_14/092728/yolo/10th/four_frame_result/0/txt/KeyFrameTrajectory0910_new.txt
firstmap_new_trajectory_path: ''
firstmap_trajectory_path: /mnt/sda/coex_data/long_sequence/result_2025_04_14_092728/mono_result/KeyFrameTrajectory09.txt
nextmap_new_trajectory_path: ''
nextmap_trajectory_path: /mnt/sda/coex_data/long_sequence/result_2025_04_14_092728/mono_result/KeyFrameTrajectory10.txt
out_path: /home/youngsun/vslam/corl/ConnectingMaps/ORB-SLAM1/2025_04_14/092728/connected_long.txt
root_dir: /mnt/sda/coex_data/long_sequence
sequences:
- '00'
- '01'
- '02'
- '03'
- '04'
- '05'
- '06'
- '07'
- 08
- 09
- '10'
time_str: 092728
txt_input_path: ''
txt_parsed_path: /home/youngsun/vslam/corl/ConnectingMaps/ORB-SLAM1/2025_04_14/092728/yolo/10th/four_frame_result/0/txt/images_parsed.txt
